#!/usr/bin/env bash
# Transfers a file from our client to a server
#
# Variables
current_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
script_name=$(basename "$BASH_SOURCE")
file_to_transfer="$1"
destination_ip="$2"
remote_user="ubuntu"
private_key="$HOME/.ssh/school"

if [ $# -eq 2 ]; then
        scp -i "$private_key" -o StrictHostKeyChecking=no "$current_path"/"$file_to_transfer" "$remote_user"@"$destination_ip":/home/"$remote_user"/
else
        echo -e "Usage: $script_name PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
